apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: e2e-tests-java-quarkus-jkinhlph
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/e2e-tests-java-quarkus-jkinhlph:azure-6bd18de0d22319642b31c6a7853c5cbc2f0d10e1
        name: container-image  
